In [2]:
import numpy as np

In [3]:
a = [1,2,3]

In [4]:
a

[1, 2, 3]

In [5]:
b = np.array(a)

In [6]:
b

array([1, 2, 3])

In [7]:
type(a)

list

In [8]:
type(b)

numpy.ndarray

In [9]:
c = [[1,2,3],[4,5,6]]

In [10]:
c

[[1, 2, 3], [4, 5, 6]]

In [11]:
d = np.array(c)

In [12]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
d.shape

(2, 3)

In [14]:
np.zeros

<function numpy.zeros>

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(4)

array([0.43132515, 0.42920299, 0.37246334, 0.33893499])

In [23]:
np.random.rand(3,6)

array([[0.0365784 , 0.29966784, 0.03961252, 0.16727799, 0.41462781,
        0.92020975],
       [0.41330567, 0.00741406, 0.29849617, 0.57123889, 0.46167281,
        0.09992951],
       [0.29288652, 0.54357482, 0.64169258, 0.29369279, 0.20449507,
        0.36413536]])

In [24]:
np.random.randn(4)

array([0.35029419, 0.78311319, 1.52208198, 1.84982576])

In [25]:
np.random.normal(4.0,1.0,100)

array([3.96891017, 5.63348214, 3.38862929, 5.46312825, 3.88353581,
       2.64732137, 5.49350186, 5.69955436, 3.8513842 , 4.56397075,
       3.19219462, 5.54406432, 3.99226015, 3.40289046, 4.27772672,
       4.70340439, 4.92354039, 1.17267301, 2.18039057, 4.37542965,
       4.57285248, 4.34722356, 5.03621466, 6.10642916, 4.64742232,
       2.54840783, 2.85718194, 4.2314427 , 4.50299458, 4.84231048,
       4.01535894, 4.5377841 , 3.61264671, 4.53534496, 3.64787059,
       3.80922615, 3.24460984, 4.6683054 , 5.98066862, 4.33275328,
       3.44374445, 4.96272927, 4.90147421, 4.01915391, 3.4798022 ,
       5.49786053, 2.52850026, 5.41384751, 3.87264558, 5.27508985,
       4.04814388, 3.82809516, 3.423045  , 6.43012233, 5.34169467,
       4.80655093, 5.52723545, 4.1511378 , 4.38587413, 5.91477543,
       2.89067707, 5.37615929, 1.74199107, 3.68675014, 3.25333199,
       4.3605155 , 2.94394049, 4.47466075, 4.02340477, 5.8416036 ,
       3.3308048 , 4.6259683 , 2.50457128, 3.9018955 , 3.86888

In [26]:
np.random.seed(4)
np.random.rand(4)

array([0.96702984, 0.54723225, 0.97268436, 0.71481599])

In [28]:
e = np.arange(1,20)

In [29]:
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [30]:
e[4]

5

In [31]:
e[6:17]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [32]:
e[6:]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
d[0]

array([1, 2, 3])

In [35]:
d[0][2]

3

In [36]:
d + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
d * 5

array([[ 5, 10, 15],
       [20, 25, 30]])